---
  deployment:
    tasks:
      - export REPOPATH=/home3/waytoiti/repositories/Wit
      - export DEPLOYPATH=/home3/waytoiti/public_html
      - rm -rf $DEPLOYPATH/*  # Clears old files to avoid conflicts
      - cp -r $REPOPATH/public/* $DEPLOYPATH/  # Copies only the needed files
  